version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: vet-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vet_db
    networks:
      - vet_network

  app:
    container_name: vet-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - vet_network

networks:
  vet_network:
    driver: bridge